### ISSUE TITLE
autogen.sh hardcodes the prefix

### ISSUE THREAD

**Issue by MathieuDuponchelle** [HSU-ANT/gstpeaq#1]
It's possible with gstreamer libraries and most projects with an autogen.sh script to pass --prefix to the script and have it be forwarded to configure, it would be great to have it be the case for gstpeaq as well :)

**Comment by martinholters** [comment]
Sounds like a good idea. Want to open a PR?

**Comment by martinholters** [comment]
I guess not, then.

I've just pushed 13954d1c099325adc9f3c508974f8ec79bf17200 which makes `autogen.sh` pass any options on to `configure`. They are appended to the hardcoded ones, so a given `--prefix` takes precedence over the default.

**Comment by MathieuDuponchelle** [comment]
Thanks, sorry filed and forgot :)

**Comment by martinholters** [comment]
No worries. The change was super-simple, it just took me a while to get around doing it. If you feel like something more sophisticated would be useful, you're still invited to open a PR with a proposal :wink:
