### ISSUE TITLE
Failed to load plugin

### ISSUE THREAD

**Issue by hocksionglim** [HSU-ANT/gstpeaq#10]
Hi, when i got these error message when I run peaq1-0.exe, does anyone knows what is wrong? 

(peaq-1.0.exe:45436): GStreamer-WARNING **: 16:31:23.596: Failed to load plugin 'C:\gstreamer\1.0\x86_64\lib\gstreamer-1.0\gstclosedcaption.dll': 'C:\gstreamer\1.0\x86_64\lib\gstreamer-1.0\gstclosedcaption.dll': The specified procedure could not be found.

(peaq-1.0.exe:45436): GStreamer-WARNING **: 16:31:24.989: Failed to load plugin 'C:\gstreamer\1.0\x86_64\lib\gstreamer-1.0\gstopenh264.dll': 'C:\gstreamer\1.0\x86_64\lib\gstreamer-1.0\gstopenh264.dll': The specified procedure could not be found.

(peaq-1.0.exe:45436): GStreamer-WARNING **: 16:31:26.245: Failed to load plugin 'C:\gstreamer\1.0\x86_64\lib\gstreamer-1.0\gstpango.dll': 'C:\gstreamer\1.0\x86_64\lib\gstreamer-1.0\gstpango.dll': The specified procedure could not be found.

**Comment by martinholters** [comment]
Note that these are only warnings and these three plugins should be irrelevant for GstPEAQ. So does it still work? (That said, figuring out the cause of these warnings and fixing would still be good.)

**Comment by ViktorMann** [comment]
Hello martin, can you please help me. I am studying in Germany and want to use your PEAQ for answering my Bachelorthesis. But it is not working on my WIN10 Notebook. Maybe you can give me a guideline to make it run. Please help - if you understand german i can explain much better.

Kind Regards

Viktor Mann

**Comment by martinholters** [comment]
Sure, feel free to contact me by email.

**Comment by martinholters** [comment]
Without additional information (at least, whether there is an error in addition to these warnings), I don't see anything actionable here. Please comment if the problem persists.
