### ISSUE TITLE
Building on Windows 10 x64 with Visual Studio 2019

### ISSUE THREAD

**Issue by jonnor** [HSU-ANT/gstpeaq#11]
Hi,
thank a  lot for this open implementation of PEAQ! It built, installed and ran without issues on my Arch Linux system.

However on Windows 10 with Visual Studio 2019 I had a couple of minor issues. I installed Gstreamer 1.x for x64 per the instructions. Then when using the provided Visual Studio files from git (develop branch), I got the following issues.

- Had to use Retarget Solution to updated to a C runtime that was installed with VS code. `v142` in my case
- Compile errors due to gstreamer/glib header files not found. Turns out default build config is win32, and will then only look for 32bit gstreamer headers. Changing Target Platform in Visual Studio to x64 made things compile. 
- Linker errors in `msvcrt`. To fix this I added `ucrt.lib` and `vcruntime.lib` to the linker config. Some random forum post says this is expected VS versions post 2015. This made the .dll and .exe link correctly.
- Now got issue that the `peaq` Gstreamer element was not found, despite using `--gst-plugin-load`. To fix, renamed gstpeaq-1.0 to gstpeaq.dll - as per https://github.com/HSU-ANT/gstpeaq/issues/7#issuecomment-482453327

I have made the Visual Studio changes in this branch: https://github.com/jonnor/gstpeaq/tree/fix-build-vs2019
Not sure it is pull request quality, but hopefully it can be useful for others along with the hints in this post.

**Comment by martinholters** [comment]
I've left a comment over there re. the 64bit thing.

I think it would be best to just remove the GStremer-0.10 stuff and then drop the `-1.0` suffix everywhere, making the renaming unnecessary. But even without that, if you go over `INSTALL.Windows` to update the required versions (and fix what you spot otherwise) and double-check the 32bit/64bit thing, I'd be happy to receive a PR.

**Comment by martinholters** [comment]
I believe this is fixed by #16 and moreover, as the Windows build is now tested as part of CI, it hopefully shouldn't regress.
Please comment if any issues remain.

**Comment by jonnor** [comment]
I am not able to test right now, but I checked the PR and it looks great.
The CI setup is good reference for how to build it, and the availability of
binaries simplifies usage a lot. Thank you!

FYI, we are working on a paper referencing GstPEAQ these days.
