### ISSUE TITLE
How can I install the app in a new ubuntu 20.04 machine?

### ISSUE THREAD

**Issue by wusq121** [HSU-ANT/gstpeaq#17]
I installed the gstreamer-1.0 by following commands:

`apt-get install libgstreamer1.0-0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-doc gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-gl gstreamer1.0-gtk3 gstreamer1.0-qt5 gstreamer1.0-pulseaudio`
and
`sudo apt-get install -y libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev gstreamer1.0-plugins-good libgstreamer-plugins-good1.0-dev libgstreamer-plugins-bad1.0-dev gstreamer1.0-libav`

but when I run 
`sh autogen.sh`

get a message

checking for gst-launch-1.0... gst-launch-1.0
./configure: line 9748: syntax error near unexpected token `1.10,--flavour'
./configure: line 9748: `GTK_DOC_CHECK(1.10,--flavour no-tmpl)'

**Comment by martinholters** [comment]
Try to also
```
apt-get install gtk-doc-tools w3-dtd-mathml
```

**Comment by martinholters** [comment]
Does this work for you?

**Comment by wusq121** [comment]
> 
> 
> Does this work for you?

Thank you very much for your help, although there will be no errors mentioned earlier, but there were other errors in executing the make command. I've given up using this tool.

**Comment by martinholters** [comment]
I've just veirfifed that in an `ubuntu::20.04` docker container, this sequence of commands succeeds:
```
apt-get update
apt-get install -y git
git clone https://github.com/HSU-ANT/gstpeaq.git
cd gstpeaq
apt-get install -y gcc git2cl gtk-doc-tools w3-dtd-mathml libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev gstreamer1.0-tools gstreamer1.0-plugins-base
./autogen.sh
make
make install
```
So without further information, it's possible to know why your build fails. Therefore, I'm closing this issue, but feel free to report back if you decide you want to give building it another try and need help.
