### ISSUE TITLE
Is there any way to printout the individual MOV

### ISSUE THREAD

**Issue by harmomyshoes** [HSU-ANT/gstpeaq#20]
Very Grateful for this library. I have hired the EC2 on the AWS; it is working as expected.
I just wonder is there any way I can get individual MOV from the basic model or advanced model?

**Comment by martinholters** [comment]
Sorry for missing this for so long.

If you instantiate the GStreamer pipeline yourself, you can set the `console-output` property of the `peaq` element to true and then retrieve the MOVs from stdout. Not pretty, but should work.

**Comment by harmomyshoes** [comment]
That is very useful! Will try that
