### ISSUE TITLE
Strange results on a comparisons with increasing noise

### ISSUE THREAD

**Issue by ctralie** [HSU-ANT/gstpeaq#21]
Hello,
First of all, thank you for this software.  It is amazing to have a resource like this.

I am trying to make sense of some strange results I'm getting in the advanced mode with additive noise.  I'm researching audio watermarking, and I've found that the advanced mode gives more sensible results overall for the techniques I've been trying. 

However, I stumbled across a strange regime for simple additive noise on one of my examples.  Here are three example files I tested that show the potential issue:
https://drive.google.com/drive/folders/1H20JmErEECJpbf_fvpgiWF-CM5lHKwJD?usp=drive_link

I'm using the command line tool, and when I run the following command on a 30 second clip of Michael Jackson's "Smooth Criminal" versus a version with additive noise at 7dB PSNR
```
peaq --advanced ref.wav psnr7.wav
```
I get
```
Objective Difference Grade: -3.768
Distortion Index: -2.935
```

which makes sense; this sounds like crap.  But when I go to an even lower PSNR of 4dB
```
peaq --advanced ref.wav psnr4.wav
```
I get this
```
Objective Difference Grade: -0.141
Distortion Index: 2.365
```

which is very strange.  In fact, there's an entire regime of very high noise in which the ODG suddenly peaks back up towards 0 where it shouldn't:
![UniformNoise](https://github.com/HSU-ANT/gstpeaq/assets/1270246/6159e4be-ebae-478d-b6e7-2915a334e74e)

Interestingly, the basic version gives better results on this example:
![UniformNoise_Basic](https://github.com/HSU-ANT/gstpeaq/assets/1270246/44133ddd-5924-46ca-b14f-3eff7a172a9a)

However, advanced has given much better results on my watermarking experiments overall.  In particular, I find the basic result gives some strange results even on very simple watermarking techniques like echo hiding (I'm happy to provide those details as well).  So I trust the advanced mode more.  But the example I'm attaching here gave me pause.

I apologize if I'm missing something simple, and I hope you'll be able to shed some light on this!
Sincerely,
Chris Tralie

**Comment by ctralie** [comment]
Actually, I wonder if this is at all related to #6 .  You'll notice there are a few brief moments of silence in the reference clip.  But the clip is 30 seconds long.

**Comment by ctralie** [comment]
Actually, I should note one more thing I found when implementing echo hiding for audio watermarking.  When using an impulse response of the form

h[n] = delta[n] + alpha*delta[n-d]

for a delay d of 50 samples for a "0" bit in a window or 75 for a "1" bit in a window, I saw that the ODG decreases as alpha moves from 0 to 0.5, but then increases for a while between 0.5 and 1

![image](https://github.com/HSU-ANT/gstpeaq/assets/1270246/e0d8606d-cfda-444f-93e8-007f0a3631b0)

Code here:
https://github.com/ctralie/EchoHiding/blob/main/ODGExperiments.ipynb

There could be a perceptual explanation for this, but I also found it strange

**Comment by martinholters** [comment]
Well, the PEAQ algorithm has been tuned for audio coding with small impairments, so for any other types of impairments, the result should be taking with more than a grain of salt.
Doing some inspection of the model out variables during processing, one may find an explanation for the phenomena you are observing, but I don't have the bandwidth to do so at the moment. Also, I'm not sure what any findings thus obtained could lead to.

Anyway, as I doubt this is an issue of the implementation and more a characteristic of the implemented standard, I'm closing this. But feel free to report back if you have doubts.
