### ISSUE TITLE
How to pass format in caps? 

### ISSUE THREAD

**Issue by p-q-s-r** [HSU-ANT/gstpeaq#22]
While trying to pass the format as s16le I get the error:-
GST_PIPELINE grammer.y: could not link refsrc to peaq, peaq can't handle caps audio/x-raw, format=(string) s16le

**Comment by martinholters** [comment]
Yes, GstPEAQ is quite limited in supported input caps:
https://github.com/HSU-ANT/gstpeaq/blob/0b9315ecdaac6440db757eed8eabfa0cfc7dfd8e/src/gstpeaq.c#L147-L152
The solution usually is to place an `audioconvert` element in front of it, like
https://github.com/HSU-ANT/gstpeaq/blob/0b9315ecdaac6440db757eed8eabfa0cfc7dfd8e/src/gstpeaq.c#L44-L53
I don't think there is much to be gained by making GstPEAQ itself capable of understanding more formats, so closing, but feel free to comment if you disagree.
