### ISSUE TITLE
Verification of the conformance failed

### ISSUE THREAD

**Issue by chrisycw03** [HSU-ANT/gstpeaq#23]
Hello,

I am using Ubuntu 22.04.4 with gstreamer 1.0. I built GstPEAQ 0.6.1 by 
```./configure --with-conformance-dataset=./CONFORMANCE/ CC="gcc -lm"```
And the .WAV files in ```./CONFORMANCE/``` are from https://www.itu.int/rec/R-REC-BS.1387

When I ```make check```, I got one FAIL.
The message in ```test-suite.log``` was
```
=======================================
   GstPEAQ 0.6.1: src/test-suite.log
=======================================

# TOTAL: 3
# PASS:  2
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: checkconformanceresults.sh
================================

Basic version:
acodsna 0.449 1.297 FAILED
```
It seemed that the result of DI was very different from the reference value.
How can I fix this problem?

**Comment by martinholters** [comment]
Hm, this is weird... The fix would be to use the same test items as I did, which differ from those provided by the ITU nowadays. It's obviously quite long ago that I acquired my copy of the reference items, but I don't see any indication on the ITU site they were ever changed. But apparently, they must have. And for the newly downloaded items, I also get:
```
acodsna 0.449 1.297 FAILED
```
So it seems the course of action to take would be to update https://github.com/HSU-ANT/gstpeaq/blob/0b9315ecdaac6440db757eed8eabfa0cfc7dfd8e/doc/conformance_basic_table.xml and https://github.com/HSU-ANT/gstpeaq/blob/0b9315ecdaac6440db757eed8eabfa0cfc7dfd8e/doc/conformance_advanced_table.xml to reflect the results obtained with the new WAV files. However, trying again whether changing any of the settings in https://github.com/HSU-ANT/gstpeaq/blob/0b9315ecdaac6440db757eed8eabfa0cfc7dfd8e/src/settings.h improves conformance when using the new WAVs would also seem indicated. Finally, I've noticed that there was an update to BS.1387-2 last year. Would be worth checking whether that contains any corrections/clarifications, but it appears there is no version history/changelog. Oh well, what a mess...

**Comment by martinholters** [comment]
As was mentioned to me elsewhere, the conformance test items presently available for download at the ITU site appear to be corrupted. 

> How can I fix this problem?

By asking ITU, I'm afraid. So while this is an unfortunate situation, I don't think anything can be done here, hence closing the issue.
