### ISSUE TITLE
Peaq could not be instantiated

### ISSUE THREAD

**Issue by shukaizheng** [HSU-ANT/gstpeaq#3]
My install steps follow:
1. wget .tar file of version 0.6.1,  and untar it.
2. install the plugin as: ''sudo apt-get install libgstreamer0.10-dev libgstreamer-plugins-base0.10-dev''
3. ./configure
4. sudo make & make install
No errors throw in these step. 
But some wrong when I run peaq:
![image](https://user-images.githubusercontent.com/4609486/33863716-17841990-df24-11e7-9c6a-cc2a30ee084b.png)
Could you help me? Thanks.

**Comment by shukaizheng** [comment]
My system:
![image](https://user-images.githubusercontent.com/4609486/33863762-534ee7e8-df24-11e7-8afc-b3b03f28782c.png)

**Comment by martinholters** [comment]
That error looks like either `libgstpeaq.so` was installed in the wrong place or it cannot be loaded for some other reason. Can you try `peaq --gst-debug-level=4 source.wav line_syn.wav` and see whether the output contains anything pointing at the problem? Also, can you try to locate where `libgstpeaq.so` got installed and then try `peaq --gst-plugin-load=<path_you_determined>/libgstpeaq.so ...`? Is there a bunch of `libgst*.so` files in the same location?

**Comment by shukaizheng** [comment]
Thank you for your kindly reply. It works when I set pram "--gst-plugin-load".And I rewatched your install document and find the detail( export GST_PLUGIN_PATH .eg ).It‘s my fault not read it carefully.
The result of process:
![image](https://user-images.githubusercontent.com/4609486/33874872-469bf536-df5b-11e7-9620-87cb56d8ea79.png)
I don't know the meaning of Distortion Index, what''s different between with DOG？Thanks。

**Comment by martinholters** [comment]
Ok, glad that fixed it. You can just copy the `libgstpeaq.so` to the location where the other GStreamer plugins reside (`/usr/lib/gstreamer-1.0/` or  `/usr/lib/x86_64-linux-gnu/gstreamer-1.0/` ?) and don't have to specify the path upon every invocation.

The distortion index is some intermediate result which is just mapped with a non-linear function to the ODG. You can safely ignore it.
