### ISSUE TITLE
gstreamer error

### ISSUE THREAD

**Issue by Manikantaks** [HSU-ANT/gstpeaq#9]
I could not resolve this issue when i run configure file on debian.   

configure: error: Package requirements (gstreamer-0.10 >= 0.10.14
			  gstreamer-base-0.10 >= 0.10.11
			  gstreamer-fft-0.10 >= 0.10.15) were not met:

could you guide me on this .

**Comment by martinholters** [comment]
Try with `apt-get install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev`. (Or, if you are on an outdated system, `apt-get install libgstreamer0.10-dev libgstreamer-plugins-base0.10-dev`.)

**Comment by Manikantaks** [comment]
Thanks @martinholters  it got resolved . How to execute this with refer and test file . I could not find neither peag file nor peaq command . I didn't find any documents .

**Comment by martinholters** [comment]
After `make install`, `peaq` should be installed somewhere on the path, `/usr/local/bin` by default. Hard to say what's wrong if it isn't without further information. (Note that the default `libdir` may not be the best choice, see `INSTALL`, but you should be able to invoke `peaq` anyway.)

**Comment by Manikantaks** [comment]
Thanks. its working !!

**Comment by Manikantaks** [comment]
Could i get any report of the result . 
I just got the message like this : 
Objective Difference Grade: 0.207
Distortion Index: 5.771

**Comment by martinholters** [comment]
The objective difference grade is the result. What kind of report would you like to get?

**Comment by Manikantaks** [comment]
Thanks @martinholters  .I understand objective difference grade (ODG)  is like unit if measurement .
I need help - I want test a audio file ( call recorded file). I am not getting reference file  to compare. 
How could i get reference file ?

**Comment by martinholters** [comment]
Er, PEAQ compares a processed/impaired version (test item) against the original/unimpaired version (reference item). If you don't have the reference, PEAQ is not the right tool for you.

> How could i get reference file ?

That is highly application specific, of course. In general, if you only have an impaired version, there is no going back to the original. (That would be fantastic, wouldn't it?)

**Comment by martinholters** [comment]
The original build problem seems solved, the remaining questions are not actionable, so closing.
